-- ============================================================================
-- PEX TEAM (Performance Excellence) VIEWS (India & Brazil)
-- Purpose: Performance analysis — targets vs actuals, tenure impact, team benchmarks
-- Key questions: "Target attainment by pod?", "Revenue vs target?", "Tenure vs performance?", "Points pacing?"
-- ============================================================================

-- ── India ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW `tough-zoo-475011-s6.cognizant_poc.v_pex_team_india` AS
SELECT
  -- Revenue metrics (for actuals)
  Revenue_records.rev_company_id                        AS company_id,
  Revenue_records.company_name                          AS company_name,
  Revenue_records.revenue_qtd                           AS revenue_qtd,
  Revenue_records.revenue_yesterday                     AS revenue_yesterday,
  Revenue_records.revenue_prev_7_days                   AS revenue_prev_7_days,
  Revenue_records.revenue_prev_28d                      AS revenue_prev_28_days,
  Revenue_records.capped_running_total_revenue          AS capped_running_total_revenue,
  Revenue_records.capped_running_total_revenue_in_quarter AS capped_running_total_revenue_in_quarter,
  Revenue_records.capped_revenue_eoq_forecast           AS capped_revenue_eoq_forecast,
  Revenue_records.in_quarter_qtd_revenue                AS in_quarter_qtd_revenue,
  Revenue_records.rolling_qtd_revenue                   AS rolling_qtd_revenue,
  Revenue_records.revenue_pre_assignment                AS revenue_pre_assignment,
  Revenue_records.total_ad_spend                        AS total_ad_spend,
  Revenue_records.seq_rev1                              AS sequential_revenue,
  Revenue_records.pitchstatus                           AS revenue_pitch_status,
  Revenue_records.rev_year_quarter                      AS year_quarter,
  Revenue_records.rev_pod_name                          AS pod_name,
  Revenue_records.onboarding_program                    AS program,
  Revenue_records.onboarding_region                     AS region,
  Revenue_records.onboarding_market                     AS market,
  Revenue_records.vendor_name                           AS vendor_name,
  Revenue_records.is_pitched                            AS is_pitched,
  Revenue_records.is_adopted                            AS is_adopted,
  Revenue_records.cur_qtr                               AS is_current_quarter,
  Revenue_records.prev_qtr                              AS is_previous_quarter,
  Revenue_records.days_in_qtr                           AS days_in_quarter,
  Revenue_records.current_dc_lifecycle_week             AS lifecycle_week,
  Revenue_records.cumulative_active_days                AS cumulative_active_days,
  Revenue_records.remaining_dc_days_in_qtr              AS remaining_dc_days_in_quarter,
  Revenue_records.days_since_gt_assigned                AS days_since_assigned,
  Revenue_records.company_ks_owner                      AS company_ks_owner,
  Revenue_records.revenue_accounts_amount               AS revenue_accounts_amount,

  -- Productivity metrics (for performance scoring)
  productivity_records.pp_company_id                    AS prod_company_id,
  productivity_records.pointswoncapped                  AS points_won,
  productivity_records.pointswonandlivecapped           AS points_won_live,
  productivity_records.isliveuaa                        AS is_live_uaa,
  productivity_records.isuaa                            AS is_uaa,
  productivity_records.is_pitched                       AS prod_is_pitched,
  productivity_records.is_adopted                       AS prod_is_adopted,
  productivity_records.pitchstatus                      AS prod_pitch_status,
  productivity_records.firstpitched_date                AS first_pitched_date,
  productivity_records.onboarding_pod_name              AS prod_pod_name,
  productivity_records.onboarding_program               AS prod_program,
  productivity_records.is_assisted_sign_up              AS is_assisted_sign_up,
  productivity_records.company_ks_owner                 AS prod_ks_owner,
  productivity_records.productivity_accounts_amount     AS productivity_accounts_amount,
  productivity_records.pp_year_quarter                  AS prod_year_quarter,

  -- Session metrics (for activity analysis)
  session_data.sessions                                 AS total_sessions,
  session_data.completed_sessions                       AS completed_sessions,
  session_data.contact_attempt_sessions                 AS contact_attempt_sessions,
  session_data.answered_sessions                        AS answered_sessions,
  session_data.meet_session                             AS meet_sessions,
  session_data.meet_answered_sessions                   AS meet_answered_sessions,
  session_data.talk_time_seconds                        AS talk_time_seconds,
  session_data.phone_talk_time_seconds                  AS phone_talk_time_seconds,
  session_data.completed_phone_calls                    AS completed_phone_calls,
  session_data.final_status                             AS session_final_status,
  session_data.podname                                  AS session_pod_name,
  session_data.rep_ldap                                 AS rep_ldap,

  -- TCSAT (for quality-performance correlation)
  tcsat_records.q1_osat                                 AS osat_score,
  tcsat_records.q2_rsat                                 AS rsat_score,
  tcsat_records.q3_psat                                 AS psat_score,
  tcsat_records.response_start_date                     AS tcsat_response_date,
  tcsat_records.pod_name                                AS tcsat_pod_name,
  tcsat_records.program                                 AS tcsat_program,
  tcsat_records.quarter                                 AS tcsat_quarter,
  tcsat_records.tcsat_accounts_amount                   AS tcsat_accounts_amount,

  -- People (tenure for performance correlation)
  people_data.ldap                                      AS ldap,
  people_data.tenure_in_months                          AS tenure_months,
  people_data.tenure_in_years                           AS tenure_years,
  people_data.hiring_date                               AS hiring_date,
  people_data.role                                      AS people_role,
  people_data.project                                   AS people_project,
  people_data.status                                    AS people_status,
  people_data.exit_quarter                              AS exit_quarter,
  people_data.supervisor                                AS supervisor,

  -- Targets (core for PEX — actuals vs targets)
  tgt.target                                            AS revenue_target,
  tgt.points_target__eoq                                AS points_target_eoq,
  tgt.uaa_target__eoq                                   AS uaa_target_eoq,
  tgt.tt_rev                                            AS target_track_revenue,
  tgt.tt_points                                         AS target_track_points,
  tgt.tt_uaa                                            AS target_track_uaa,
  tgt.ldap                                              AS target_ldap,
  tgt.pod_name                                          AS target_pod_name,
  tgt.program                                           AS target_program,
  tgt.year_quarter                                      AS target_year_quarter,

  -- Top-level
  off_program,
  off_podname,
  off_onboarding_region,
  imp,
  loss,
  pitched

FROM `tough-zoo-475011-s6.cognizant_poc.bqdata`
WHERE off_onboarding_region = 'India';


-- ── Brazil ─────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW `tough-zoo-475011-s6.cognizant_poc.v_pex_team_brazil` AS
SELECT
  Revenue_records.rev_company_id                        AS company_id,
  Revenue_records.company_name                          AS company_name,
  Revenue_records.revenue_qtd                           AS revenue_qtd,
  Revenue_records.revenue_yesterday                     AS revenue_yesterday,
  Revenue_records.revenue_prev_7_days                   AS revenue_prev_7_days,
  Revenue_records.revenue_prev_28d                      AS revenue_prev_28_days,
  Revenue_records.capped_running_total_revenue          AS capped_running_total_revenue,
  Revenue_records.capped_running_total_revenue_in_quarter AS capped_running_total_revenue_in_quarter,
  Revenue_records.capped_revenue_eoq_forecast           AS capped_revenue_eoq_forecast,
  Revenue_records.in_quarter_qtd_revenue                AS in_quarter_qtd_revenue,
  Revenue_records.rolling_qtd_revenue                   AS rolling_qtd_revenue,
  Revenue_records.revenue_pre_assignment                AS revenue_pre_assignment,
  Revenue_records.total_ad_spend                        AS total_ad_spend,
  Revenue_records.seq_rev1                              AS sequential_revenue,
  Revenue_records.pitchstatus                           AS revenue_pitch_status,
  Revenue_records.rev_year_quarter                      AS year_quarter,
  Revenue_records.rev_pod_name                          AS pod_name,
  Revenue_records.onboarding_program                    AS program,
  Revenue_records.onboarding_region                     AS region,
  Revenue_records.onboarding_market                     AS market,
  Revenue_records.vendor_name                           AS vendor_name,
  Revenue_records.is_pitched                            AS is_pitched,
  Revenue_records.is_adopted                            AS is_adopted,
  Revenue_records.cur_qtr                               AS is_current_quarter,
  Revenue_records.prev_qtr                              AS is_previous_quarter,
  Revenue_records.days_in_qtr                           AS days_in_quarter,
  Revenue_records.current_dc_lifecycle_week             AS lifecycle_week,
  Revenue_records.cumulative_active_days                AS cumulative_active_days,
  Revenue_records.remaining_dc_days_in_qtr              AS remaining_dc_days_in_quarter,
  Revenue_records.days_since_gt_assigned                AS days_since_assigned,
  Revenue_records.company_ks_owner                      AS company_ks_owner,
  Revenue_records.revenue_accounts_amount               AS revenue_accounts_amount,
  productivity_records.pp_company_id                    AS prod_company_id,
  productivity_records.pointswoncapped                  AS points_won,
  productivity_records.pointswonandlivecapped           AS points_won_live,
  productivity_records.isliveuaa                        AS is_live_uaa,
  productivity_records.isuaa                            AS is_uaa,
  productivity_records.is_pitched                       AS prod_is_pitched,
  productivity_records.is_adopted                       AS prod_is_adopted,
  productivity_records.pitchstatus                      AS prod_pitch_status,
  productivity_records.firstpitched_date                AS first_pitched_date,
  productivity_records.onboarding_pod_name              AS prod_pod_name,
  productivity_records.onboarding_program               AS prod_program,
  productivity_records.is_assisted_sign_up              AS is_assisted_sign_up,
  productivity_records.company_ks_owner                 AS prod_ks_owner,
  productivity_records.productivity_accounts_amount     AS productivity_accounts_amount,
  productivity_records.pp_year_quarter                  AS prod_year_quarter,
  session_data.sessions                                 AS total_sessions,
  session_data.completed_sessions                       AS completed_sessions,
  session_data.contact_attempt_sessions                 AS contact_attempt_sessions,
  session_data.answered_sessions                        AS answered_sessions,
  session_data.meet_session                             AS meet_sessions,
  session_data.meet_answered_sessions                   AS meet_answered_sessions,
  session_data.talk_time_seconds                        AS talk_time_seconds,
  session_data.phone_talk_time_seconds                  AS phone_talk_time_seconds,
  session_data.completed_phone_calls                    AS completed_phone_calls,
  session_data.final_status                             AS session_final_status,
  session_data.podname                                  AS session_pod_name,
  session_data.rep_ldap                                 AS rep_ldap,
  tcsat_records.q1_osat                                 AS osat_score,
  tcsat_records.q2_rsat                                 AS rsat_score,
  tcsat_records.q3_psat                                 AS psat_score,
  tcsat_records.response_start_date                     AS tcsat_response_date,
  tcsat_records.pod_name                                AS tcsat_pod_name,
  tcsat_records.program                                 AS tcsat_program,
  tcsat_records.quarter                                 AS tcsat_quarter,
  tcsat_records.tcsat_accounts_amount                   AS tcsat_accounts_amount,
  people_data.ldap                                      AS ldap,
  people_data.tenure_in_months                          AS tenure_months,
  people_data.tenure_in_years                           AS tenure_years,
  people_data.hiring_date                               AS hiring_date,
  people_data.role                                      AS people_role,
  people_data.project                                   AS people_project,
  people_data.status                                    AS people_status,
  people_data.exit_quarter                              AS exit_quarter,
  people_data.supervisor                                AS supervisor,
  tgt.target                                            AS revenue_target,
  tgt.points_target__eoq                                AS points_target_eoq,
  tgt.uaa_target__eoq                                   AS uaa_target_eoq,
  tgt.tt_rev                                            AS target_track_revenue,
  tgt.tt_points                                         AS target_track_points,
  tgt.tt_uaa                                            AS target_track_uaa,
  tgt.ldap                                              AS target_ldap,
  tgt.pod_name                                          AS target_pod_name,
  tgt.program                                           AS target_program,
  tgt.year_quarter                                      AS target_year_quarter,
  off_program,
  off_podname,
  off_onboarding_region,
  imp,
  loss,
  pitched
FROM `tough-zoo-475011-s6.cognizant_poc.bqdata`
WHERE off_onboarding_region = 'Brazil';
