"""SQL scope injector — CRITICAL SECURITY LAYER.

Uses ``sqlglot`` to parse any SQL generated by any agent and inject a
``WHERE region = '<scope_value>'`` clause before execution. This ensures
that non-admin users can never see data outside their permitted region,
regardless of what SQL the LLM produces.
"""

from __future__ import annotations

import logging

import sqlglot
from sqlglot import exp

logger = logging.getLogger(__name__)


def inject_scope(sql: str, scope_region: str | None) -> str:
    """Inject a region scope filter into the given SQL.

    Args:
        sql: The raw SQL query generated by an agent.
        scope_region: The region to restrict to, or ``None`` for unrestricted
                      (admin users).

    Returns:
        The SQL with an additional ``region = '<scope_value>'`` predicate
        AND-ed into every WHERE clause (or added as a new WHERE clause if
        none exists).
    """
    if scope_region is None:
        logger.debug("Scope injection skipped (admin / unrestricted)")
        return sql

    try:
        parsed = sqlglot.parse(sql)
    except sqlglot.errors.ErrorLevel:
        logger.error("Failed to parse SQL for scope injection: %s", sql)
        raise ValueError(f"Unparseable SQL: {sql}")

    results: list[str] = []
    for statement in parsed:
        if statement is None:
            continue
        _inject_into_statement(statement, scope_region)
        results.append(statement.sql(dialect="bigquery"))

    injected = "; ".join(results)
    logger.info("Scope-injected SQL: %s", injected)
    return injected


def _inject_into_statement(statement: exp.Expression, scope_region: str) -> None:
    """Recursively inject region filters into SELECT statements."""
    # Handle subqueries first
    for subquery in statement.find_all(exp.Select):
        _inject_where(subquery, scope_region)


def _inject_where(select: exp.Select, scope_region: str) -> None:
    """Add ``region = '<scope>'`` to a single SELECT's WHERE clause."""
    region_filter = sqlglot.parse_one(
        f"region = '{scope_region}'",
        into=exp.Condition,
    )

    existing_where = select.find(exp.Where)
    if existing_where is not None:
        # AND the new condition into the existing WHERE
        new_condition = exp.And(
            this=existing_where.this,
            expression=region_filter,
        )
        existing_where.set("this", new_condition)
    else:
        # Create a new WHERE clause
        select.set("where", exp.Where(this=region_filter))
