"""User context resolved from JWT + BigQuery user_access table."""

from __future__ import annotations

from dataclasses import dataclass


# ── View mapping — CORE RBAC ENFORCEMENT ────────────────────────────────
# Maps (role, region) → BigQuery view name.
# These views are pre-created and act as the data security layer.
VIEW_MAP: dict[tuple[str, str], str] = {
    # Seller — individual sales performance
    ("seller", "India"): "v_seller_india",
    ("seller", "Brazil"): "v_seller_brazil",
    # Ops Lead — team operations oversight
    ("ops_lead", "India"): "v_ops_lead_india",
    ("ops_lead", "Brazil"): "v_ops_lead_brazil",
    # Quality Analyst — TCSAT & session quality
    ("quality_analyst", "India"): "v_quality_analyst_india",
    ("quality_analyst", "Brazil"): "v_quality_analyst_brazil",
    # Data Contributor — broad analytical access (no PII)
    ("data_contributor", "India"): "v_data_contributor_india",
    ("data_contributor", "Brazil"): "v_data_contributor_brazil",
    # System Administrator — full access
    ("sys_admin", "India"): "v_sys_admin_india",
    ("sys_admin", "Brazil"): "v_sys_admin_brazil",
    # PEX Team — performance excellence
    ("pex_team", "India"): "v_pex_team_india",
    ("pex_team", "Brazil"): "v_pex_team_brazil",
}

# ── Schema descriptions per role (for agent prompts) ───────────────────
# These schemas tell the LLM exactly what columns exist so it generates correct SQL.
VIEW_SCHEMAS: dict[str, dict] = {
    "seller": {
        "description": (
            "Seller performance view — revenue metrics, productivity (points/UAA), "
            "session/call activity, and targets, filtered to the seller's region."
        ),
        "columns": [
            # Revenue
            {"name": "company_id", "type": "INT64", "description": "Company identifier (from revenue records)"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "revenue_qtd", "type": "FLOAT64", "description": "Revenue quarter-to-date"},
            {"name": "revenue_yesterday", "type": "FLOAT64", "description": "Revenue generated yesterday"},
            {"name": "revenue_prev_7_days", "type": "FLOAT64", "description": "Revenue in prior 7 days"},
            {"name": "revenue_prev_14_days", "type": "FLOAT64", "description": "Revenue in prior 14 days"},
            {"name": "revenue_prev_28_days", "type": "FLOAT64", "description": "Revenue in prior 28 days"},
            {"name": "revenue_prev_7_to_14_days", "type": "FLOAT64", "description": "Revenue between 7-14 days ago"},
            {"name": "capped_running_total_revenue", "type": "FLOAT64", "description": "Capped cumulative revenue"},
            {"name": "capped_running_total_revenue_in_quarter", "type": "FLOAT64", "description": "Capped cumulative revenue in current quarter"},
            {"name": "capped_assignment_revenue", "type": "FLOAT64", "description": "Capped revenue from assignment"},
            {"name": "capped_revenue_eoq_forecast", "type": "FLOAT64", "description": "End-of-quarter revenue forecast (capped)"},
            {"name": "in_quarter_qtd_revenue", "type": "FLOAT64", "description": "In-quarter QTD revenue"},
            {"name": "rolling_qtd_revenue", "type": "FLOAT64", "description": "Rolling QTD revenue"},
            {"name": "revenue_pre_assignment", "type": "FLOAT64", "description": "Revenue before assignment"},
            {"name": "total_ad_spend", "type": "FLOAT64", "description": "Total advertising spend"},
            {"name": "sequential_revenue", "type": "FLOAT64", "description": "Sequential revenue metric"},
            {"name": "revenue_pitch_status", "type": "STRING", "description": "Pitch status from revenue data"},
            {"name": "year_quarter", "type": "STRING", "description": "Year-quarter (e.g. 2025Q1)"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "program", "type": "STRING", "description": "Onboarding program name"},
            {"name": "region", "type": "STRING", "description": "Onboarding region"},
            {"name": "market", "type": "STRING", "description": "Market segment"},
            {"name": "is_pitched", "type": "BOOL", "description": "Whether account has been pitched"},
            {"name": "is_adopted", "type": "BOOL", "description": "Whether account has been adopted"},
            {"name": "is_current_quarter", "type": "BOOL", "description": "True if current quarter record"},
            {"name": "is_previous_quarter", "type": "BOOL", "description": "True if previous quarter record"},
            {"name": "days_in_quarter", "type": "INT64", "description": "Total days in the quarter"},
            {"name": "lifecycle_week", "type": "INT64", "description": "Current DC lifecycle week"},
            {"name": "lifecycle_day", "type": "INT64", "description": "DC lifecycle day"},
            {"name": "cumulative_active_days", "type": "INT64", "description": "Cumulative active days"},
            {"name": "remaining_dc_days", "type": "INT64", "description": "Remaining DC days"},
            {"name": "remaining_dc_days_in_quarter", "type": "INT64", "description": "Remaining DC days in quarter"},
            {"name": "days_since_assigned", "type": "INT64", "description": "Days since GT was assigned"},
            {"name": "revenue_accounts_amount", "type": "STRING", "description": "Revenue accounts amount tier"},
            # Productivity
            {"name": "points_won", "type": "INT64", "description": "Points won (capped)"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won and live (capped)"},
            {"name": "is_live_uaa", "type": "INT64", "description": "Is live UAA (1/0)"},
            {"name": "is_uaa", "type": "INT64", "description": "Is UAA (1/0)"},
            {"name": "prod_is_pitched", "type": "BOOL", "description": "Pitched status from productivity"},
            {"name": "prod_is_adopted", "type": "BOOL", "description": "Adopted status from productivity"},
            {"name": "prod_pitch_status", "type": "STRING", "description": "Pitch status from productivity"},
            {"name": "first_pitched_date", "type": "STRING", "description": "Date of first pitch"},
            {"name": "productivity_accounts_amount", "type": "STRING", "description": "Productivity accounts amount tier"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Year-quarter from productivity"},
            # Sessions
            {"name": "total_sessions", "type": "INT64", "description": "Total session count"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempt sessions"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Google Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet sessions that were answered"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Total talk time in seconds"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time in seconds"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed phone calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Final status of session"},
            # Targets
            {"name": "revenue_target", "type": "FLOAT64", "description": "Revenue target"},
            {"name": "points_target_eoq", "type": "FLOAT64", "description": "Points target end-of-quarter"},
            {"name": "uaa_target_eoq", "type": "FLOAT64", "description": "UAA target end-of-quarter"},
            {"name": "target_track_revenue", "type": "FLOAT64", "description": "Revenue target tracking"},
            {"name": "target_track_points", "type": "FLOAT64", "description": "Points target tracking"},
            {"name": "target_track_uaa", "type": "FLOAT64", "description": "UAA target tracking"},
            # Top-level
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod name"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering onboarding region"},
            {"name": "imp", "type": "INT64", "description": "Impressions count"},
            {"name": "loss", "type": "INT64", "description": "Loss count"},
            {"name": "pitched", "type": "INT64", "description": "Pitched count"},
        ],
    },
    "ops_lead": {
        "description": (
            "Ops Lead view — full team operations: revenue, productivity, session activity, "
            "TCSAT satisfaction, people/tenure data, and targets. Used for team management and performance tracking."
        ),
        "columns": [
            # Revenue
            {"name": "company_id", "type": "INT64", "description": "Company identifier"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "revenue_qtd", "type": "FLOAT64", "description": "Revenue quarter-to-date"},
            {"name": "revenue_yesterday", "type": "FLOAT64", "description": "Revenue yesterday"},
            {"name": "revenue_prev_7_days", "type": "FLOAT64", "description": "Revenue in prior 7 days"},
            {"name": "revenue_prev_14_days", "type": "FLOAT64", "description": "Revenue in prior 14 days"},
            {"name": "revenue_prev_28_days", "type": "FLOAT64", "description": "Revenue in prior 28 days"},
            {"name": "capped_running_total_revenue", "type": "FLOAT64", "description": "Capped cumulative revenue"},
            {"name": "capped_running_total_revenue_in_quarter", "type": "FLOAT64", "description": "Capped cumulative revenue in quarter"},
            {"name": "capped_assignment_revenue", "type": "FLOAT64", "description": "Capped assignment revenue"},
            {"name": "capped_revenue_eoq_forecast", "type": "FLOAT64", "description": "EOQ revenue forecast"},
            {"name": "in_quarter_qtd_revenue", "type": "FLOAT64", "description": "In-quarter QTD revenue"},
            {"name": "rolling_qtd_revenue", "type": "FLOAT64", "description": "Rolling QTD revenue"},
            {"name": "revenue_pre_assignment", "type": "FLOAT64", "description": "Revenue pre-assignment"},
            {"name": "total_ad_spend", "type": "FLOAT64", "description": "Total ad spend"},
            {"name": "sequential_revenue", "type": "FLOAT64", "description": "Sequential revenue"},
            {"name": "revenue_pitch_status", "type": "STRING", "description": "Revenue pitch status"},
            {"name": "year_quarter", "type": "STRING", "description": "Year-quarter"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "program", "type": "STRING", "description": "Program name"},
            {"name": "region", "type": "STRING", "description": "Region"},
            {"name": "market", "type": "STRING", "description": "Market"},
            {"name": "vendor_name", "type": "STRING", "description": "Vendor name"},
            {"name": "is_pitched", "type": "BOOL", "description": "Pitched flag"},
            {"name": "is_adopted", "type": "BOOL", "description": "Adopted flag"},
            {"name": "is_current_quarter", "type": "BOOL", "description": "Current quarter flag"},
            {"name": "is_previous_quarter", "type": "BOOL", "description": "Previous quarter flag"},
            {"name": "days_in_quarter", "type": "INT64", "description": "Days in quarter"},
            {"name": "lifecycle_week", "type": "INT64", "description": "DC lifecycle week"},
            {"name": "cumulative_active_days", "type": "INT64", "description": "Cumulative active days"},
            {"name": "remaining_dc_days_in_quarter", "type": "INT64", "description": "Remaining DC days in quarter"},
            {"name": "days_since_assigned", "type": "INT64", "description": "Days since assigned"},
            {"name": "company_ks_owner", "type": "STRING", "description": "Company KS owner"},
            {"name": "primary_ks_owner", "type": "STRING", "description": "Primary KS owner"},
            {"name": "secondary_ks_owner", "type": "STRING", "description": "Secondary KS owner"},
            {"name": "revenue_accounts_amount", "type": "STRING", "description": "Revenue accounts amount tier"},
            # Productivity
            {"name": "prod_company_id", "type": "INT64", "description": "Productivity company ID"},
            {"name": "points_won", "type": "INT64", "description": "Points won (capped)"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won and live"},
            {"name": "is_live_uaa", "type": "INT64", "description": "Live UAA flag"},
            {"name": "is_uaa", "type": "INT64", "description": "UAA flag"},
            {"name": "prod_is_pitched", "type": "BOOL", "description": "Pitched from productivity"},
            {"name": "prod_is_adopted", "type": "BOOL", "description": "Adopted from productivity"},
            {"name": "prod_pitch_status", "type": "STRING", "description": "Pitch status from productivity"},
            {"name": "first_pitched_date", "type": "STRING", "description": "First pitched date"},
            {"name": "prod_pod_name", "type": "STRING", "description": "Productivity pod name"},
            {"name": "prod_program", "type": "STRING", "description": "Productivity program"},
            {"name": "is_assisted_sign_up", "type": "BOOL", "description": "Assisted sign up flag"},
            {"name": "prod_ks_owner", "type": "STRING", "description": "Productivity KS owner"},
            {"name": "productivity_accounts_amount", "type": "STRING", "description": "Productivity accounts tier"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Productivity year-quarter"},
            # Sessions (detailed for ops)
            {"name": "session_company_id", "type": "INT64", "description": "Session company ID"},
            {"name": "total_sessions", "type": "INT64", "description": "Total sessions"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempts"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet answered sessions"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Talk time in seconds"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time in seconds"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed phone calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Session final status"},
            {"name": "session_pod_name", "type": "STRING", "description": "Session pod name"},
            {"name": "rep_ldap", "type": "STRING", "description": "Rep LDAP identifier"},
            {"name": "session_vendor_program", "type": "STRING", "description": "Session vendor program"},
            {"name": "session_company_name", "type": "STRING", "description": "Session company name"},
            {"name": "speakeasy_accounts_amount", "type": "STRING", "description": "Speakeasy accounts amount"},
            {"name": "session_start_hour", "type": "INT64", "description": "Session start hour (0-23)"},
            {"name": "rep_country", "type": "STRING", "description": "Rep country"},
            # TCSAT
            {"name": "tcsat_company_id", "type": "INT64", "description": "TCSAT company ID"},
            {"name": "tcsat_company_name", "type": "STRING", "description": "TCSAT company name"},
            {"name": "osat_score", "type": "FLOAT64", "description": "Overall satisfaction score (OSAT)"},
            {"name": "rsat_score", "type": "FLOAT64", "description": "Relationship satisfaction (RSAT)"},
            {"name": "psat_score", "type": "FLOAT64", "description": "Product satisfaction (PSAT)"},
            {"name": "tcsat_response_date", "type": "DATE", "description": "TCSAT response date"},
            {"name": "satisfaction_response", "type": "STRING", "description": "Satisfaction text response"},
            {"name": "tcsat_pod_name", "type": "STRING", "description": "TCSAT pod name"},
            {"name": "tcsat_program", "type": "STRING", "description": "TCSAT program"},
            {"name": "tcsat_has_comments", "type": "BOOL", "description": "Has comments flag"},
            {"name": "tcsat_quarter", "type": "STRING", "description": "TCSAT quarter"},
            {"name": "tcsat_accounts_amount", "type": "STRING", "description": "TCSAT accounts amount tier"},
            # People
            {"name": "ldap", "type": "STRING", "description": "Employee LDAP"},
            {"name": "tenure_months", "type": "INT64", "description": "Tenure in months"},
            {"name": "tenure_years", "type": "INT64", "description": "Tenure in years"},
            {"name": "hiring_date", "type": "STRING", "description": "Hiring date"},
            {"name": "people_role", "type": "STRING", "description": "Employee role"},
            {"name": "people_project", "type": "STRING", "description": "Employee project"},
            {"name": "people_status", "type": "STRING", "description": "Employee status (active/inactive)"},
            {"name": "exit_quarter", "type": "STRING", "description": "Exit quarter (if applicable)"},
            {"name": "supervisor", "type": "STRING", "description": "Supervisor name"},
            # Targets
            {"name": "revenue_target", "type": "FLOAT64", "description": "Revenue target"},
            {"name": "points_target_eoq", "type": "FLOAT64", "description": "Points target EOQ"},
            {"name": "uaa_target_eoq", "type": "FLOAT64", "description": "UAA target EOQ"},
            {"name": "target_track_revenue", "type": "FLOAT64", "description": "Revenue target tracking"},
            {"name": "target_track_points", "type": "FLOAT64", "description": "Points target tracking"},
            {"name": "target_track_uaa", "type": "FLOAT64", "description": "UAA target tracking"},
            {"name": "target_ldap", "type": "STRING", "description": "Target LDAP"},
            {"name": "target_pod_name", "type": "STRING", "description": "Target pod name"},
            {"name": "target_program", "type": "STRING", "description": "Target program"},
            {"name": "target_year_quarter", "type": "STRING", "description": "Target year-quarter"},
            # Top-level
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod name"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering region"},
            {"name": "off_division_id", "type": "INT64", "description": "Division ID"},
            {"name": "off_primary_marketing_objective", "type": "ARRAY<STRING>", "description": "Primary marketing objectives"},
            {"name": "imp", "type": "INT64", "description": "Impressions"},
            {"name": "loss", "type": "INT64", "description": "Losses"},
            {"name": "pitched", "type": "INT64", "description": "Pitched count"},
        ],
    },
    "quality_analyst": {
        "description": (
            "Quality Analyst view — TCSAT satisfaction scores (OSAT/RSAT/PSAT), session quality metrics, "
            "and productivity correlation data. Focused on service quality analysis."
        ),
        "columns": [
            # TCSAT
            {"name": "meeting_id", "type": "INT64", "description": "Meeting identifier"},
            {"name": "company_id", "type": "INT64", "description": "TCSAT company ID"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "osat_score", "type": "FLOAT64", "description": "Overall satisfaction (OSAT, 1-5 scale)"},
            {"name": "rsat_score", "type": "FLOAT64", "description": "Relationship satisfaction (RSAT, 1-5 scale)"},
            {"name": "psat_score", "type": "FLOAT64", "description": "Product satisfaction (PSAT, 1-5 scale)"},
            {"name": "response_date", "type": "DATE", "description": "Survey response date"},
            {"name": "satisfaction_response", "type": "STRING", "description": "Satisfaction text response"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "program", "type": "STRING", "description": "Program name"},
            {"name": "response_id", "type": "STRING", "description": "Unique response identifier"},
            {"name": "has_comments", "type": "BOOL", "description": "Whether response includes comments"},
            {"name": "meeting_owner", "type": "STRING", "description": "Meeting owner / seller"},
            {"name": "quarter", "type": "STRING", "description": "Quarter (e.g. 2025Q1)"},
            {"name": "region", "type": "STRING", "description": "TCSAT region"},
            {"name": "sub_region", "type": "STRING", "description": "TCSAT sub-region"},
            {"name": "tcsat_accounts_amount", "type": "STRING", "description": "TCSAT accounts amount tier"},
            # Sessions
            {"name": "total_sessions", "type": "INT64", "description": "Total sessions"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempts"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet answered sessions"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Talk time in seconds"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time in seconds"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed phone calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Session final status"},
            {"name": "session_pod_name", "type": "STRING", "description": "Session pod name"},
            {"name": "rep_ldap", "type": "STRING", "description": "Rep LDAP"},
            {"name": "session_vendor_program", "type": "STRING", "description": "Session vendor program"},
            {"name": "session_start_hour", "type": "INT64", "description": "Session start hour"},
            # Productivity
            {"name": "points_won", "type": "INT64", "description": "Points won"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won and live"},
            {"name": "is_pitched", "type": "BOOL", "description": "Pitched flag"},
            {"name": "is_adopted", "type": "BOOL", "description": "Adopted flag"},
            {"name": "pitch_status", "type": "STRING", "description": "Pitch status"},
            {"name": "prod_pod_name", "type": "STRING", "description": "Productivity pod name"},
            {"name": "prod_program", "type": "STRING", "description": "Productivity program"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Productivity year-quarter"},
            # Top-level
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod name"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering region"},
        ],
    },
    "data_contributor": {
        "description": (
            "Data Contributor view — broad analytical access across revenue, productivity, sessions, "
            "TCSAT, people (no PII), and targets. Designed for cross-dimensional analysis and data enrichment."
        ),
        "columns": [
            # Revenue (full)
            {"name": "company_id", "type": "INT64", "description": "Company ID"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "revenue_qtd", "type": "FLOAT64", "description": "Revenue QTD"},
            {"name": "revenue_yesterday", "type": "FLOAT64", "description": "Revenue yesterday"},
            {"name": "revenue_prev_7_days", "type": "FLOAT64", "description": "Revenue prev 7 days"},
            {"name": "revenue_prev_14_days", "type": "FLOAT64", "description": "Revenue prev 14 days"},
            {"name": "revenue_prev_28_days", "type": "FLOAT64", "description": "Revenue prev 28 days"},
            {"name": "revenue_prev_7_to_14_days", "type": "FLOAT64", "description": "Revenue 7-14 days ago"},
            {"name": "capped_running_total_revenue", "type": "FLOAT64", "description": "Capped running total revenue"},
            {"name": "capped_running_total_revenue_in_quarter", "type": "FLOAT64", "description": "Capped running total in quarter"},
            {"name": "capped_running_total_revenue_rollover", "type": "FLOAT64", "description": "Capped running total rollover"},
            {"name": "capped_assignment_revenue", "type": "FLOAT64", "description": "Capped assignment revenue"},
            {"name": "capped_revenue_eoq_forecast", "type": "FLOAT64", "description": "EOQ forecast"},
            {"name": "in_quarter_qtd_revenue", "type": "FLOAT64", "description": "In-quarter QTD revenue"},
            {"name": "rolling_qtd_revenue", "type": "FLOAT64", "description": "Rolling QTD revenue"},
            {"name": "revenue_pre_assignment", "type": "FLOAT64", "description": "Revenue pre-assignment"},
            {"name": "total_ad_spend", "type": "FLOAT64", "description": "Total ad spend"},
            {"name": "sequential_revenue", "type": "FLOAT64", "description": "Sequential revenue"},
            {"name": "division_country", "type": "STRING", "description": "Division country"},
            {"name": "revenue_pitch_status", "type": "STRING", "description": "Revenue pitch status"},
            {"name": "year_quarter", "type": "STRING", "description": "Year-quarter"},
            {"name": "revenue_refresh_date", "type": "STRING", "description": "Revenue refresh date"},
            {"name": "rev_refresh_date", "type": "STRING", "description": "Rev refresh date"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "onboarding_pod_id", "type": "STRING", "description": "Onboarding pod ID"},
            {"name": "program", "type": "STRING", "description": "Program"},
            {"name": "region", "type": "STRING", "description": "Region"},
            {"name": "market", "type": "STRING", "description": "Market"},
            {"name": "vendor_name", "type": "STRING", "description": "Vendor name"},
            {"name": "is_pitched", "type": "BOOL", "description": "Pitched flag"},
            {"name": "is_adopted", "type": "BOOL", "description": "Adopted flag"},
            {"name": "is_current_quarter", "type": "BOOL", "description": "Current quarter flag"},
            {"name": "is_previous_quarter", "type": "BOOL", "description": "Previous quarter flag"},
            {"name": "quarter_id", "type": "INT64", "description": "Quarter ID"},
            {"name": "days_in_quarter", "type": "INT64", "description": "Days in quarter"},
            {"name": "lifecycle_week", "type": "INT64", "description": "Lifecycle week"},
            {"name": "lifecycle_day", "type": "INT64", "description": "Lifecycle day"},
            {"name": "cumulative_active_days", "type": "INT64", "description": "Cumulative active days"},
            {"name": "remaining_dc_days", "type": "INT64", "description": "Remaining DC days"},
            {"name": "remaining_dc_days_in_quarter", "type": "INT64", "description": "Remaining DC days in quarter"},
            {"name": "days_since_assigned", "type": "INT64", "description": "Days since assigned"},
            {"name": "revenue_accounts_amount", "type": "STRING", "description": "Revenue accounts tier"},
            # Productivity
            {"name": "prod_company_id", "type": "INT64", "description": "Productivity company ID"},
            {"name": "points_won", "type": "INT64", "description": "Points won"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won live"},
            {"name": "is_live_uaa", "type": "INT64", "description": "Live UAA flag"},
            {"name": "is_uaa", "type": "INT64", "description": "UAA flag"},
            {"name": "prod_is_pitched", "type": "BOOL", "description": "Productivity pitched flag"},
            {"name": "prod_is_adopted", "type": "BOOL", "description": "Productivity adopted flag"},
            {"name": "prod_pitch_status", "type": "STRING", "description": "Productivity pitch status"},
            {"name": "first_pitched_date", "type": "STRING", "description": "First pitched date"},
            {"name": "prod_pod_name", "type": "STRING", "description": "Productivity pod name"},
            {"name": "prod_program", "type": "STRING", "description": "Productivity program"},
            {"name": "is_assisted_sign_up", "type": "BOOL", "description": "Assisted sign up"},
            {"name": "productivity_accounts_amount", "type": "STRING", "description": "Productivity accounts tier"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Productivity year-quarter"},
            {"name": "prod_region", "type": "STRING", "description": "Productivity region"},
            {"name": "prod_market", "type": "STRING", "description": "Productivity market"},
            {"name": "prod_refresh_date", "type": "STRING", "description": "Productivity refresh date"},
            # Sessions
            {"name": "session_company_id", "type": "INT64", "description": "Session company ID"},
            {"name": "total_sessions", "type": "INT64", "description": "Total sessions"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempts"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet answered"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Talk time seconds"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time seconds"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed phone calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Session final status"},
            {"name": "session_pod_name", "type": "STRING", "description": "Session pod name"},
            {"name": "session_vendor_program", "type": "STRING", "description": "Session vendor program"},
            {"name": "session_company_name", "type": "STRING", "description": "Session company name"},
            {"name": "speakeasy_accounts_amount", "type": "STRING", "description": "Speakeasy accounts amount"},
            {"name": "session_start_hour", "type": "INT64", "description": "Session start hour"},
            {"name": "session_market_region", "type": "STRING", "description": "Session market region"},
            {"name": "session_market", "type": "STRING", "description": "Session market"},
            # TCSAT
            {"name": "tcsat_company_id", "type": "INT64", "description": "TCSAT company ID"},
            {"name": "tcsat_company_name", "type": "STRING", "description": "TCSAT company name"},
            {"name": "osat_score", "type": "FLOAT64", "description": "OSAT score"},
            {"name": "rsat_score", "type": "FLOAT64", "description": "RSAT score"},
            {"name": "psat_score", "type": "FLOAT64", "description": "PSAT score"},
            {"name": "tcsat_response_date", "type": "DATE", "description": "TCSAT response date"},
            {"name": "satisfaction_response", "type": "STRING", "description": "Satisfaction response"},
            {"name": "tcsat_pod_name", "type": "STRING", "description": "TCSAT pod name"},
            {"name": "tcsat_program", "type": "STRING", "description": "TCSAT program"},
            {"name": "tcsat_has_comments", "type": "BOOL", "description": "Has comments"},
            {"name": "tcsat_quarter", "type": "STRING", "description": "TCSAT quarter"},
            {"name": "tcsat_region", "type": "STRING", "description": "TCSAT region"},
            {"name": "tcsat_sub_region", "type": "STRING", "description": "TCSAT sub-region"},
            {"name": "tcsat_accounts_amount", "type": "STRING", "description": "TCSAT accounts tier"},
            # People (no PII)
            {"name": "tenure_months", "type": "INT64", "description": "Tenure in months"},
            {"name": "tenure_years", "type": "INT64", "description": "Tenure in years"},
            {"name": "people_role", "type": "STRING", "description": "Employee role"},
            {"name": "people_project", "type": "STRING", "description": "Employee project"},
            {"name": "people_status", "type": "STRING", "description": "Employee status"},
            # Targets
            {"name": "revenue_target", "type": "FLOAT64", "description": "Revenue target"},
            {"name": "points_target_eoq", "type": "FLOAT64", "description": "Points target EOQ"},
            {"name": "uaa_target_eoq", "type": "FLOAT64", "description": "UAA target EOQ"},
            {"name": "target_track_revenue", "type": "FLOAT64", "description": "Revenue target tracking"},
            {"name": "target_track_points", "type": "FLOAT64", "description": "Points target tracking"},
            {"name": "target_track_uaa", "type": "FLOAT64", "description": "UAA target tracking"},
            {"name": "target_pod_name", "type": "STRING", "description": "Target pod name"},
            {"name": "target_program", "type": "STRING", "description": "Target program"},
            {"name": "target_year_quarter", "type": "STRING", "description": "Target year-quarter"},
            # Top-level
            {"name": "off_division_id", "type": "INT64", "description": "Division ID"},
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_primary_marketing_objective", "type": "ARRAY<STRING>", "description": "Marketing objectives"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering region"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod name"},
            {"name": "imp", "type": "INT64", "description": "Impressions"},
            {"name": "loss", "type": "INT64", "description": "Losses"},
            {"name": "pitched", "type": "INT64", "description": "Pitched count"},
        ],
    },
    "sys_admin": {
        "description": (
            "System Administrator view — full unrestricted access to all data dimensions: "
            "revenue, productivity, sessions, TCSAT, people (including PII), and targets. "
            "Used for system debugging, data validation, and administration."
        ),
        "columns": [
            # This role has ALL columns. The schema prompt lists them for the LLM.
            # Revenue
            {"name": "company_id", "type": "INT64", "description": "Company ID"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "revenue_qtd", "type": "FLOAT64", "description": "Revenue QTD"},
            {"name": "revenue_yesterday", "type": "FLOAT64", "description": "Revenue yesterday"},
            {"name": "revenue_prev_7_days", "type": "FLOAT64", "description": "Revenue prev 7d"},
            {"name": "revenue_prev_14_days", "type": "FLOAT64", "description": "Revenue prev 14d"},
            {"name": "revenue_prev_28_days", "type": "FLOAT64", "description": "Revenue prev 28d"},
            {"name": "revenue_prev_7_to_14_days", "type": "FLOAT64", "description": "Revenue 7-14d ago"},
            {"name": "capped_running_total_revenue", "type": "FLOAT64", "description": "Capped running total"},
            {"name": "capped_running_total_revenue_in_quarter", "type": "FLOAT64", "description": "Capped in-quarter"},
            {"name": "capped_running_total_revenue_rollover", "type": "FLOAT64", "description": "Capped rollover"},
            {"name": "capped_assignment_revenue", "type": "FLOAT64", "description": "Capped assignment rev"},
            {"name": "capped_revenue_eoq_forecast", "type": "FLOAT64", "description": "EOQ forecast"},
            {"name": "in_quarter_qtd_revenue", "type": "FLOAT64", "description": "In-quarter QTD"},
            {"name": "rolling_qtd_revenue", "type": "FLOAT64", "description": "Rolling QTD"},
            {"name": "revenue_pre_assignment", "type": "FLOAT64", "description": "Pre-assignment rev"},
            {"name": "total_ad_spend", "type": "FLOAT64", "description": "Ad spend"},
            {"name": "sequential_revenue", "type": "FLOAT64", "description": "Seq revenue 1"},
            {"name": "sequential_revenue_2", "type": "INT64", "description": "Seq revenue 2"},
            {"name": "division_country", "type": "STRING", "description": "Division country"},
            {"name": "revenue_pitch_status", "type": "STRING", "description": "Pitch status"},
            {"name": "year_quarter", "type": "STRING", "description": "Year-quarter"},
            {"name": "revenue_refresh_date", "type": "STRING", "description": "Revenue refresh date"},
            {"name": "rev_refresh_date", "type": "STRING", "description": "Rev refresh date"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "onboarding_pod_id", "type": "STRING", "description": "Onboarding pod ID"},
            {"name": "program", "type": "STRING", "description": "Program"},
            {"name": "region", "type": "STRING", "description": "Region"},
            {"name": "market", "type": "STRING", "description": "Market"},
            {"name": "vendor_name", "type": "STRING", "description": "Vendor"},
            {"name": "is_pitched", "type": "BOOL", "description": "Pitched"},
            {"name": "is_adopted", "type": "BOOL", "description": "Adopted"},
            {"name": "is_current_quarter", "type": "BOOL", "description": "Current qtr"},
            {"name": "is_previous_quarter", "type": "BOOL", "description": "Prev qtr"},
            {"name": "quarter_id", "type": "INT64", "description": "Quarter ID"},
            {"name": "days_in_quarter", "type": "INT64", "description": "Days in qtr"},
            {"name": "lifecycle_week", "type": "INT64", "description": "Lifecycle week"},
            {"name": "lifecycle_day", "type": "INT64", "description": "Lifecycle day"},
            {"name": "cumulative_active_days", "type": "INT64", "description": "Active days"},
            {"name": "remaining_dc_days", "type": "INT64", "description": "Remaining DC days"},
            {"name": "remaining_dc_days_in_quarter", "type": "INT64", "description": "Remaining DC days in qtr"},
            {"name": "days_since_assigned", "type": "INT64", "description": "Days since assigned"},
            {"name": "company_ks_owner", "type": "STRING", "description": "KS owner"},
            {"name": "primary_ks_owner", "type": "STRING", "description": "Primary KS owner"},
            {"name": "secondary_ks_owner", "type": "STRING", "description": "Secondary KS owner"},
            {"name": "revenue_accounts_amount", "type": "STRING", "description": "Rev accounts tier"},
            # Productivity
            {"name": "prod_company_id", "type": "INT64", "description": "Prod company ID"},
            {"name": "points_won", "type": "INT64", "description": "Points won"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won live"},
            {"name": "is_live_uaa", "type": "INT64", "description": "Live UAA"},
            {"name": "is_uaa", "type": "INT64", "description": "UAA"},
            {"name": "prod_is_pitched", "type": "BOOL", "description": "Prod pitched"},
            {"name": "prod_is_adopted", "type": "BOOL", "description": "Prod adopted"},
            {"name": "prod_pitch_status", "type": "STRING", "description": "Prod pitch status"},
            {"name": "first_pitched_date", "type": "STRING", "description": "First pitched"},
            {"name": "prod_pod_name", "type": "STRING", "description": "Prod pod"},
            {"name": "prod_program", "type": "STRING", "description": "Prod program"},
            {"name": "is_assisted_sign_up", "type": "BOOL", "description": "Assisted signup"},
            {"name": "prod_ks_owner", "type": "STRING", "description": "Prod KS owner"},
            {"name": "productivity_accounts_amount", "type": "STRING", "description": "Prod accounts tier"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Prod year-qtr"},
            {"name": "prod_region", "type": "STRING", "description": "Prod region"},
            {"name": "prod_market", "type": "STRING", "description": "Prod market"},
            {"name": "prod_refresh_date", "type": "STRING", "description": "Prod refresh date"},
            # Sessions
            {"name": "session_company_id", "type": "INT64", "description": "Session company ID"},
            {"name": "total_sessions", "type": "INT64", "description": "Total sessions"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempts"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet answered"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Talk time (s)"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time (s)"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Session status"},
            {"name": "session_pod_name", "type": "STRING", "description": "Session pod"},
            {"name": "rep_ldap", "type": "STRING", "description": "Rep LDAP"},
            {"name": "session_vendor_program", "type": "STRING", "description": "Session vendor program"},
            {"name": "session_company_name", "type": "STRING", "description": "Session company"},
            {"name": "speakeasy_accounts_amount", "type": "STRING", "description": "Speakeasy accounts"},
            {"name": "session_start_hour", "type": "INT64", "description": "Start hour"},
            {"name": "session_market_region", "type": "STRING", "description": "Session market region"},
            {"name": "session_market", "type": "STRING", "description": "Session market"},
            {"name": "rep_country", "type": "STRING", "description": "Rep country"},
            # TCSAT (all including PII)
            {"name": "meeting_id", "type": "INT64", "description": "Meeting ID"},
            {"name": "tcsat_company_id", "type": "INT64", "description": "TCSAT company ID"},
            {"name": "tcsat_company_name", "type": "STRING", "description": "TCSAT company"},
            {"name": "osat_score", "type": "FLOAT64", "description": "OSAT"},
            {"name": "rsat_score", "type": "FLOAT64", "description": "RSAT"},
            {"name": "psat_score", "type": "FLOAT64", "description": "PSAT"},
            {"name": "tcsat_response_date", "type": "DATE", "description": "Response date"},
            {"name": "satisfaction_response", "type": "STRING", "description": "Satisfaction"},
            {"name": "tcsat_recipient_email", "type": "STRING", "description": "Recipient email"},
            {"name": "tcsat_request_email", "type": "STRING", "description": "Request email"},
            {"name": "tcsat_pod_name", "type": "STRING", "description": "TCSAT pod"},
            {"name": "tcsat_program", "type": "STRING", "description": "TCSAT program"},
            {"name": "tcsat_response_id", "type": "STRING", "description": "Response ID"},
            {"name": "tcsat_ext_ref", "type": "STRING", "description": "External ref"},
            {"name": "tcsat_has_comments", "type": "BOOL", "description": "Has comments"},
            {"name": "meeting_owner", "type": "STRING", "description": "Meeting owner"},
            {"name": "seller_ldap", "type": "STRING", "description": "Seller LDAP"},
            {"name": "tcsat_quarter", "type": "STRING", "description": "TCSAT quarter"},
            {"name": "tcsat_region", "type": "STRING", "description": "TCSAT region"},
            {"name": "tcsat_sub_region", "type": "STRING", "description": "TCSAT sub-region"},
            {"name": "tcsat_accounts_amount", "type": "STRING", "description": "TCSAT accounts tier"},
            # People (full including PII)
            {"name": "ldap", "type": "STRING", "description": "LDAP"},
            {"name": "google_email", "type": "STRING", "description": "Google email"},
            {"name": "tenure_months", "type": "INT64", "description": "Tenure months"},
            {"name": "tenure_years", "type": "INT64", "description": "Tenure years"},
            {"name": "hiring_date", "type": "STRING", "description": "Hiring date"},
            {"name": "people_role", "type": "STRING", "description": "Role"},
            {"name": "people_project", "type": "STRING", "description": "Project"},
            {"name": "people_status", "type": "STRING", "description": "Status"},
            {"name": "exit_quarter", "type": "STRING", "description": "Exit quarter"},
            {"name": "supervisor", "type": "STRING", "description": "Supervisor"},
            # Targets
            {"name": "revenue_target", "type": "FLOAT64", "description": "Revenue target"},
            {"name": "points_target_eoq", "type": "FLOAT64", "description": "Points target EOQ"},
            {"name": "uaa_target_eoq", "type": "FLOAT64", "description": "UAA target EOQ"},
            {"name": "target_track_revenue", "type": "FLOAT64", "description": "TT revenue"},
            {"name": "target_track_points", "type": "FLOAT64", "description": "TT points"},
            {"name": "target_track_uaa", "type": "FLOAT64", "description": "TT UAA"},
            {"name": "target_ldap", "type": "STRING", "description": "Target LDAP"},
            {"name": "target_pod_name", "type": "STRING", "description": "Target pod"},
            {"name": "target_program", "type": "STRING", "description": "Target program"},
            {"name": "target_year_quarter", "type": "STRING", "description": "Target year-qtr"},
            # Top-level
            {"name": "off_division_id", "type": "INT64", "description": "Division ID"},
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_primary_marketing_objective", "type": "ARRAY<STRING>", "description": "Marketing objectives"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering region"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod"},
            {"name": "imp", "type": "INT64", "description": "Impressions"},
            {"name": "loss", "type": "INT64", "description": "Losses"},
            {"name": "pitched", "type": "INT64", "description": "Pitched"},
        ],
    },
    "pex_team": {
        "description": (
            "PEX Team (Performance Excellence) view — targets vs actuals, revenue performance, "
            "productivity scoring, session activity, TCSAT quality, and people tenure/status. "
            "Designed for performance benchmarking and target attainment analysis."
        ),
        "columns": [
            # Revenue
            {"name": "company_id", "type": "INT64", "description": "Company ID"},
            {"name": "company_name", "type": "STRING", "description": "Company name"},
            {"name": "revenue_qtd", "type": "FLOAT64", "description": "Revenue QTD"},
            {"name": "revenue_yesterday", "type": "FLOAT64", "description": "Revenue yesterday"},
            {"name": "revenue_prev_7_days", "type": "FLOAT64", "description": "Revenue prev 7 days"},
            {"name": "revenue_prev_28_days", "type": "FLOAT64", "description": "Revenue prev 28 days"},
            {"name": "capped_running_total_revenue", "type": "FLOAT64", "description": "Capped running total"},
            {"name": "capped_running_total_revenue_in_quarter", "type": "FLOAT64", "description": "Capped in-quarter"},
            {"name": "capped_revenue_eoq_forecast", "type": "FLOAT64", "description": "EOQ forecast"},
            {"name": "in_quarter_qtd_revenue", "type": "FLOAT64", "description": "In-quarter QTD"},
            {"name": "rolling_qtd_revenue", "type": "FLOAT64", "description": "Rolling QTD"},
            {"name": "revenue_pre_assignment", "type": "FLOAT64", "description": "Pre-assignment revenue"},
            {"name": "total_ad_spend", "type": "FLOAT64", "description": "Ad spend"},
            {"name": "sequential_revenue", "type": "FLOAT64", "description": "Sequential revenue"},
            {"name": "revenue_pitch_status", "type": "STRING", "description": "Pitch status"},
            {"name": "year_quarter", "type": "STRING", "description": "Year-quarter"},
            {"name": "pod_name", "type": "STRING", "description": "Pod name"},
            {"name": "program", "type": "STRING", "description": "Program"},
            {"name": "region", "type": "STRING", "description": "Region"},
            {"name": "market", "type": "STRING", "description": "Market"},
            {"name": "vendor_name", "type": "STRING", "description": "Vendor"},
            {"name": "is_pitched", "type": "BOOL", "description": "Pitched flag"},
            {"name": "is_adopted", "type": "BOOL", "description": "Adopted flag"},
            {"name": "is_current_quarter", "type": "BOOL", "description": "Current quarter"},
            {"name": "is_previous_quarter", "type": "BOOL", "description": "Previous quarter"},
            {"name": "days_in_quarter", "type": "INT64", "description": "Days in quarter"},
            {"name": "lifecycle_week", "type": "INT64", "description": "Lifecycle week"},
            {"name": "cumulative_active_days", "type": "INT64", "description": "Active days"},
            {"name": "remaining_dc_days_in_quarter", "type": "INT64", "description": "Remaining DC days in qtr"},
            {"name": "days_since_assigned", "type": "INT64", "description": "Days since assigned"},
            {"name": "company_ks_owner", "type": "STRING", "description": "KS owner"},
            {"name": "revenue_accounts_amount", "type": "STRING", "description": "Revenue accounts tier"},
            # Productivity
            {"name": "prod_company_id", "type": "INT64", "description": "Productivity company ID"},
            {"name": "points_won", "type": "INT64", "description": "Points won"},
            {"name": "points_won_live", "type": "INT64", "description": "Points won live"},
            {"name": "is_live_uaa", "type": "INT64", "description": "Live UAA"},
            {"name": "is_uaa", "type": "INT64", "description": "UAA"},
            {"name": "prod_is_pitched", "type": "BOOL", "description": "Prod pitched"},
            {"name": "prod_is_adopted", "type": "BOOL", "description": "Prod adopted"},
            {"name": "prod_pitch_status", "type": "STRING", "description": "Prod pitch status"},
            {"name": "first_pitched_date", "type": "STRING", "description": "First pitched date"},
            {"name": "prod_pod_name", "type": "STRING", "description": "Prod pod name"},
            {"name": "prod_program", "type": "STRING", "description": "Prod program"},
            {"name": "is_assisted_sign_up", "type": "BOOL", "description": "Assisted signup"},
            {"name": "prod_ks_owner", "type": "STRING", "description": "Prod KS owner"},
            {"name": "productivity_accounts_amount", "type": "STRING", "description": "Prod accounts tier"},
            {"name": "prod_year_quarter", "type": "STRING", "description": "Prod year-quarter"},
            # Sessions
            {"name": "total_sessions", "type": "INT64", "description": "Total sessions"},
            {"name": "completed_sessions", "type": "INT64", "description": "Completed sessions"},
            {"name": "contact_attempt_sessions", "type": "INT64", "description": "Contact attempts"},
            {"name": "answered_sessions", "type": "INT64", "description": "Answered sessions"},
            {"name": "meet_sessions", "type": "INT64", "description": "Meet sessions"},
            {"name": "meet_answered_sessions", "type": "INT64", "description": "Meet answered"},
            {"name": "talk_time_seconds", "type": "INT64", "description": "Talk time (s)"},
            {"name": "phone_talk_time_seconds", "type": "INT64", "description": "Phone talk time (s)"},
            {"name": "completed_phone_calls", "type": "INT64", "description": "Completed calls"},
            {"name": "session_final_status", "type": "STRING", "description": "Session status"},
            {"name": "session_pod_name", "type": "STRING", "description": "Session pod"},
            {"name": "rep_ldap", "type": "STRING", "description": "Rep LDAP"},
            # TCSAT
            {"name": "osat_score", "type": "FLOAT64", "description": "OSAT score"},
            {"name": "rsat_score", "type": "FLOAT64", "description": "RSAT score"},
            {"name": "psat_score", "type": "FLOAT64", "description": "PSAT score"},
            {"name": "tcsat_response_date", "type": "DATE", "description": "TCSAT response date"},
            {"name": "tcsat_pod_name", "type": "STRING", "description": "TCSAT pod"},
            {"name": "tcsat_program", "type": "STRING", "description": "TCSAT program"},
            {"name": "tcsat_quarter", "type": "STRING", "description": "TCSAT quarter"},
            {"name": "tcsat_accounts_amount", "type": "STRING", "description": "TCSAT accounts tier"},
            # People
            {"name": "ldap", "type": "STRING", "description": "LDAP"},
            {"name": "tenure_months", "type": "INT64", "description": "Tenure months"},
            {"name": "tenure_years", "type": "INT64", "description": "Tenure years"},
            {"name": "hiring_date", "type": "STRING", "description": "Hiring date"},
            {"name": "people_role", "type": "STRING", "description": "Role"},
            {"name": "people_project", "type": "STRING", "description": "Project"},
            {"name": "people_status", "type": "STRING", "description": "Status"},
            {"name": "exit_quarter", "type": "STRING", "description": "Exit quarter"},
            {"name": "supervisor", "type": "STRING", "description": "Supervisor"},
            # Targets (core for PEX)
            {"name": "revenue_target", "type": "FLOAT64", "description": "Revenue target"},
            {"name": "points_target_eoq", "type": "FLOAT64", "description": "Points target EOQ"},
            {"name": "uaa_target_eoq", "type": "FLOAT64", "description": "UAA target EOQ"},
            {"name": "target_track_revenue", "type": "FLOAT64", "description": "Revenue target tracking (progress)"},
            {"name": "target_track_points", "type": "FLOAT64", "description": "Points target tracking (progress)"},
            {"name": "target_track_uaa", "type": "FLOAT64", "description": "UAA target tracking (progress)"},
            {"name": "target_ldap", "type": "STRING", "description": "Target LDAP"},
            {"name": "target_pod_name", "type": "STRING", "description": "Target pod"},
            {"name": "target_program", "type": "STRING", "description": "Target program"},
            {"name": "target_year_quarter", "type": "STRING", "description": "Target year-quarter"},
            # Top-level
            {"name": "off_program", "type": "STRING", "description": "Offering program"},
            {"name": "off_podname", "type": "STRING", "description": "Offering pod"},
            {"name": "off_onboarding_region", "type": "STRING", "description": "Offering region"},
            {"name": "imp", "type": "INT64", "description": "Impressions"},
            {"name": "loss", "type": "INT64", "description": "Losses"},
            {"name": "pitched", "type": "INT64", "description": "Pitched count"},
        ],
    },
}


@dataclass(frozen=True, slots=True)
class UserContext:
    """Immutable context resolved from JWT + user_access table.

    Attributes:
        email:      Authenticated Google email.
        role:       One of seller, ops_lead, quality_analyst, data_contributor, sys_admin, pex_team.
        region:     Data region: India or Brazil.
        view_name:  The BigQuery view this user is authorized to query.
    """

    email: str
    role: str
    region: str
    view_name: str

    @property
    def schema_info(self) -> dict:
        """Return the schema description for this user's role."""
        return VIEW_SCHEMAS.get(self.role, {})

    @property
    def column_names(self) -> list[str]:
        """Return the column names available in this user's view."""
        schema = self.schema_info
        return [col["name"] for col in schema.get("columns", [])]

    @property
    def schema_prompt(self) -> str:
        """Build a schema description string for agent prompts."""
        schema = self.schema_info
        if not schema:
            return "No schema information available."
        lines = [f"View: {self.view_name}", f"Description: {schema['description']}", "Columns:"]
        for col in schema.get("columns", []):
            lines.append(f"  - {col['name']} ({col['type']}): {col['description']}")
        return "\n".join(lines)
